services: 
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "2004:27017"
    environment: 
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
    restart: unless-stopped
